export default function Head() {
  // todo - images need proper hash etc
  return (
    <>
      <title>TubeAlert</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" sizes="1024x1024" 
        href="https://static.tubealert.co.uk/87ee4e551f850252fd26bcd0072fc76f.ios-appicon-1024-1024.png" />
      <link rel="apple-touch-icon" sizes="180x180" 
        href="https://static.tubealert.co.uk/58ae3587ccb066ebca06b50b1b0f3251.ios-appicon-180-180.png" />
      <link rel="icon" type="image/png" sizes="32x32" 
        href="https://static.tubealert.co.uk/dcc62918f1582964d9c1e02c5f23be13.favicon-32x32.png" />
      <link rel="icon" type="image/png" sizes="16x16"
        href="https://static.tubealert.co.uk/b242342a3c61f1d6aeef3cbcc7636095.favicon-16x16.png" />
      <link rel="manifest" href="https://static.tubealert.co.uk/manifest.json" />
      <link rel="mask-icon" color="#3a3a3f" 
        href="https://static.tubealert.co.uk/478669e03d0e9505c7771e3401da24ba.safari-pinned-tab.svg" />
      <link rel="shortcut icon" type="image/x-icon" href="https://static.tubealert.co.uk/d0d19db7dc1b33590aebbf97ae94c3cb.favicon.ico" />
      <link rel="icon" type="image/x-icon" href="https://static.tubealert.co.uk/d0d19db7dc1b33590aebbf97ae94c3cb.favicon.ico" />
      <meta name="apple-mobile-web-app-title" content="TubeAlert" />
      <meta name="application-name" content="TubeAlert" />
      <meta name="msapplication-config" content="https://static.tubealert.co.uk/browserconfig.xml" />
      <meta name="theme-color" content="#3a3a3f" />
      <meta name="google-site-verification" content="dSIKzBS-efQho6aWkl9Zuq6E7Mu8bbxaz6yyM64WQPg" />
    </>
  )
}
